# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :tests do
  	run_tests(scheme: "LABS")
  end

  desc "Unit test"
  lane :unit_tests do

    update_code_signing_settings(
      path: "LABS.xcodeproj"
    )
    scan(
      scheme: "LABS",
      output_directory: "./fastlane/test_output/unit_tests_output",
      clean: true
    )
  end
end

